[package]
name = "xbd-micropython"
version = "0.1.0"
edition = "2018"
authors = ["ANIMA Minerva toolkit"]

[lib]
name = "voucher"
crate-type = ["staticlib"]

[features]
default = []
x86-validate-lts = ["minerva-voucher/validate-lts"]
#xtensa-validate-lts = ["minerva-voucher/validate-lts"]  # TODO
#x86-validate = ["minerva-voucher/validate"]  # TODO
#xtensa-validate = ["minerva-voucher/validate"]  # TODO
std = ["minerva-voucher/validate"]

[dependencies]
mcu-if = { git = "https://github.com/AnimaGUS-minerva/mcu-if", rev = "6543b39" }
minerva-voucher = { git = "https://github.com/AnimaGUS-minerva/voucher", rev = "a97f670", default-features = false }
