[package]
name = "xbd-micropython"
version = "0.1.0"
edition = "2021"
authors = ["ANIMA Minerva toolkit"]

[lib]
name = "voucher_if"
crate-type = ["staticlib"]

[features]
default = []
x86_64 = ["std"]
std = []

[dependencies]
mcu-if = { git = "https://github.com/AnimaGUS-minerva/mcu-if", rev = "984b8dd" }
minerva-voucher = { git = "https://github.com/AnimaGUS-minerva/voucher", rev = "f514c20" }
