[package]
name = "xbd-micropython"
version = "0.1.0"
edition = "2018"
authors = ["ANIMA Minerva toolkit"]

[lib]
name = "voucher"
crate-type = ["staticlib"]

[features]
default = []
std = ["minerva-voucher/validate"]

[dependencies]
mcu-if = { git = "https://github.com/AnimaGUS-minerva/mcu-if", rev = "6543b39" }
minerva-voucher = { git = "https://github.com/AnimaGUS-minerva/voucher", rev = "57b57f2", default-features = false }
