[package]
name = "xbd-micropython"
version = "0.1.0"
edition = "2018"
authors = ["ANIMA Minerva toolkit"]

[lib]
name = "voucher"
crate-type = ["staticlib"]

[dependencies]
libc-print = { git = "https://github.com/AnimaGUS-minerva/rust-libc-print", branch = "minerva" }

[target.'cfg(unix)'.dependencies]
mcu-emu = { path = "../../crates/mcu-emu" }
