#!/usr/bin/env bash

set -e

[ -z "$IDF_TOOLS_EXPORT_CMD" ] && source "$IDF_PATH/export.sh"

echo IDF_PATH: $IDF_PATH
echo RIOT_PATH: $RIOT_PATH
echo RIOT_BASE: $RIOT_BASE

#echo $PATH
# https://github.com/espressif/esp-at/issues/215#issuecomment-508597652
RIOT_XTENSA_ESP32_ELF_BIN=$RIOT_PATH/xtensa-esp32-elf/bin
echo riot-build: updating PATH to use $RIOT_XTENSA_ESP32_ELF_BIN
PATH=$RIOT_XTENSA_ESP32_ELF_BIN:$PATH

make WERROR=0 \
    ESP32_SDK_DIR=$RIOT_PATH/esp-idf \
    BOARD=esp32-wroom-32 \
    RIOTBASE=$RIOT_BASE

"$IDF_PATH/components/esptool_py/esptool/esptool.py" \
    --chip esp32 \
    elf2image \
    -o ../riot.esp32.bin \
    bin/esp32-wroom-32/*.elf  # e.g. riot.elf
ls -l ../riot.esp32.bin
