APPLICATION = main
BOARD ?= native
RIOTBASE ?= $(CURDIR)/../../../RIOT

INCLUDES += -I$(CURDIR)/../include
ARCHIVES += $(CURDIR)/../target/xtensa-esp32-none-elf/release/librustmod.a

include $(RIOTBASE)/Makefile.include
