ifeq ($(BOARD),native)
  USEMODULE += auto_init_gnrc_netif
else ifeq ($(BOARD),esp32-wroom-32)
  USEMODULE += esp_wifi
  USEMODULE += esp_now
  FEATURES_REQUIRED += arch_esp32

  USEMODULE += auto_init_gnrc_netif
else ifeq ($(BOARD),esp32-ethernet-kit-v1_0)
  USEMODULE += esp_eth
  FEATURES_REQUIRED += arch_esp32
else
  $(error BOARD set is not supported)
endif

# Include packages that pull up and auto-init the link layer.
# NOTE: 6LoWPAN will be included if IEEE802.15.4 devices are present
USEMODULE += gnrc_netdev_default

# Specify the mandatory networking modules for 6LoWPAN border router
USEMODULE += gnrc_sixlowpan_border_router_default
# Add forwarding table
USEMODULE += fib

# Optionally include RPL as a routing protocol.
#USEMODULE += gnrc_rpl