APPLICATION = riot
BOARD ?= native
RIOTBASE ?= $(CURDIR)/../../../RIOT

#INCLUDES += -I$(CURDIR)/../../libfoo-rs/include
#ARCHIVES += $(CURDIR)/../../libfoo-rs/libfoo.a

include $(RIOTBASE)/Makefile.include
