[package]
name = "xbd-base"
version = "0.1.0"
edition = "2018"
authors = ["ANIMA Minerva toolkit"]

[lib]
name = "rustmod"
crate-type = ["staticlib"]

[dependencies]
mcu-if = { path = "../../crates/mcu-if" }

[target.'cfg(unix)'.dependencies]
mcu-emu = { path = "../../crates/mcu-emu" }
