name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        build: [linux]
        include:
          - build: linux
            os: ubuntu-latest
            rust: stable
    steps:
    - uses: actions/checkout@v1
    - name: Install rustup
      run: |
        curl -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal
        rustup toolchain install ${{ matrix.rust }}
        rustup default ${{ matrix.rust }}
    - name: make init-rust-xtensa
      run: make init-rust-xtensa
    - name: Run test
      run: make ci
