name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        build: [linux]
        include:
          - build: linux
            #os: ubuntu-latest  # FIXME: ubuntu-22.04 => "native_internal.h:152:13: error: variably modified ‘__isr_stack’ at file scope"
            os: ubuntu-20.04
            rust: stable
    steps:
    - uses: actions/checkout@v1
    - name: Install rustup
      run: |
        curl -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal
        rustup toolchain install ${{ matrix.rust }}
        rustup default ${{ matrix.rust }}
    - name: make init-rust-xtensa
      run: make init-rust-xtensa
    - name: make init-esp-idf
      run: make init-esp-idf
    - name: make init-riot-xtensa
      run: make init-riot-xtensa
    - name: make init-qemu-xtensa
      run: make init-qemu-xtensa
    - name: make init-rust-toolchains
      run: make init-rust-toolchains
    - name: Run test
      run: |
          sudo apt update
          sudo apt install gcc-multilib
          sudo apt install python3-serial
          make ci
